export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_SEARCH_BAR = 'SET_SEARCH_BAR';
export const SET_POKEMON_ABILITY_DETAIL = 'SET_POKEMON_ABILITY_DETAIL';
